apiBaseUrl=http://localhost:80/openmrs
apiVersion=/ws/rest/v1
apiFullPrefix=http://localhost/openmrs/ws/rest/v1

admin.username=admin
admin.password=Admin123
admin.token=YWRtaW46QWRtaW4xMjM=

uiBaseUrl=http://gateway/openmrs/spa
browser=chrome
browserSize=1920x1080
browserRemote=http://localhost:4444/wd/hub
